version: '3'

services:
  django:
    restart: always
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    command: ["bash","startup.sh"]
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/:/usr/share/nginx/html/dist:ro
    links:
      - django
    depends_on:
      - django