
# build stage vue.js
FROM node:8.11.3
LABEL Name=dashboard-frontend Version=0.0.1

ENV REFRESHED_AT 2018-08-06
ENV http_proxy http://93.183.14.14:8080
ENV https_proxy http://93.183.14.14:8080

ENV NODE_ENV development

WORKDIR /app
COPY frontend/package.json ./
RUN rm -rf node_modules \
    && npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver \
    && npm install --save
COPY frontend ./
RUN npm run build

# Nginx
FROM nginx
COPY --from=0 /app/dist /usr/share/nginx/html
COPY nginx/conf/nginx.* /etc/ssl/
COPY nginx/conf/default.conf /etc/nginx/conf.d/
EXPOSE 80
EXPOSE 443

ENV http_proxy ""
ENV https_proxy ""
