version: '3.3'

services:
  django:
    restart: always
    build: ./backend
    image: 10.66.11.20:5000/dashboard_django
    expose:
      - '8000'
    command: ['bash', 'startup.sh']
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  nginx:
    restart: always
    build: .
    image: 10.66.11.20:5000/dashboard_nginx
    ports:
      - '80:80'
      - '443:443'
    command: ['nginx', '-g', 'daemon off;']
    links:
      - django
    depends_on:
      - django
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  dbtools:
    restart: always
    build: ./dbtools
    image: 10.66.11.20:5000/dashboard_dbtools
    command: ['bash', 'startup.sh', 'INFO']
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
