version: '3.3'

services:
  django:
    restart: always
    build: ./backend
    expose:
      - '8000'
    volumes:
      - ./backend:/app
    command: ['bash', 'startup.sh']
  nginx:
    restart: always
    build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./backend:/usr/share/nginx/html/app:ro
    command: ['nginx', '-g', 'daemon off;']
    links:
      - django
    depends_on:
      - django
  dbtools:
    restart: always
    build: ./dbtools
    command: ['bash', 'startup.sh', 'INFO']
